name: "ğŸš€ Deployment"

on:
  push:
    branches:
      - main
      - devel

permissions:
  contents: write

jobs:
  Deployment:
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/devel' }}
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      # Ã‰TAPE CRUCIALE : Forcer Node.js 22 pour supporter globSync
      - name: ğŸŸ¢ Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: ğŸ° Set up bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: ğŸ”— Install dependencies
        run: bun install

      - name: ğŸ¨ Build
        run: bun run build
        env:
          # On force le moteur de build Ã  injecter le bon prÃ©fixe
          BASE_URL: /portfolio/
      - name: ğŸš€ Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/dist
          publish_branch: pages
